import "./midBody.css"

export default function MidBody() {
    return (
        <div className="mid">
            <div className="card"><h3 className="heading">Pradhan Mantri Kisan Maandhan Yojana</h3>
                <p className="text">The Pradhan Mantri Kisan Maandhan Yojana is a crucial pension scheme designed for the welfare of small and marginal farmers in India. This scheme provides a monthly pension of INR 3000 to farmers who are 60 years of age and above. To be eligible, farmers must be between the ages of 18 and 40 and own land up to 2 hectares. The government covers the majority of the contributions required for this scheme, making it accessible to a large number of farmers. Despite its advantages, there are challenges in its implementation, such as delays in certain states and limited access for landless farmers. The application process involves visiting a common service center to complete online registration and submit required documents. The scheme aims to ensure financial security for elderly farmers who have contributed significantly to agriculture but face economic hardships in their later years.</p>
            </div>
            <div className="card"><h3 className="heading">PM-Kisan Scheme</h3>
                <p className="text">The Pradhan Mantri Kisan Samman Nidhi Yojana (PM-Kisan) is a significant initiative by the Government of India aimed at providing financial support to small and marginal farmers. Under this scheme, eligible farmers with land holdings less than two hectares receive up to INR 6000 annually as direct income support. This financial aid is crucial for enhancing the farmers' ability to meet their agricultural needs and improve their livelihoods. While the scheme has been beneficial in providing a safety net for many farmers, there are concerns regarding its impact on the fiscal health of states and the uneven implementation across different regions. Farmers can apply for the scheme through state-nominated nodal officers, common service centers, or the official online portal. The scheme represents a step towards addressing the economic challenges faced by the agricultural sector and improving the income security of farmers across the country.</p>
            </div>
            <div className="card"><h3 className="heading">Pradhan Mantri Fasal Bima Yojana</h3>
                <p className="text">The Pradhan Mantri Fasal Bima Yojana (PMFBY) is a comprehensive crop insurance scheme that aims to protect farmers from financial losses due to crop damage caused by various factors such as natural calamities, pests, and diseases. Under this scheme, farmers are required to pay a small premium—1.5% for Rabi crops, 2% for Kharif crops, and 5% for horticulture crops—with the remaining premium being subsidized by the central and state governments. The scheme covers tenant farmers, sharecroppers, and those with an insurable interest in notified crops. One of its significant advantages is the swift settlement of claims, which helps farmers recover from crop losses more efficiently. However, the scheme's implementation varies across states, and it may not be applicable in all regions. To avail of the benefits, farmers need to visit the official website, log in with their mobile ID, and provide necessary details. This initiative is crucial for mitigating the risks associated with agriculture and ensuring financial stability for farmers during challenging times.</p>
            </div>
            <div className="card"><h3 className="heading">Pradhan Mantri Krishi Sinchai Yojana (PMKSY)</h3>
                <p className="text">The Pradhan Mantri Krishi Sinchai Yojana (PMKSY) was launched with the vision of improving irrigation facilities in India, adhering to its motto "Har Khet Ko Pani" (Water to Every Field). This scheme aims to enhance the efficiency of water use in agriculture by developing a comprehensive irrigation network and improving existing water resources. It focuses on creating a robust distribution system, promoting farm-level applications, and harnessing rainwater for protective irrigation. The scheme benefits Indian farmers and those who have been cultivating leased land for at least seven years. Despite its significant goals, the implementation of PMKSY has faced challenges, such as inadequate irrigation plans and limited reach in certain states. To apply, farmers can visit the official website, log in with their email ID, and fill out the necessary details. This scheme plays a vital role in addressing the water scarcity issues faced by farmers and ensuring sustainable agricultural practices.</p>
            </div>
            <div className="card"><h3 className="heading">Pashu Kisan Credit Card Scheme</h3>
                <p className="text">The Pashu Kisan Credit Card Scheme is an initiative launched by the Government of India to support livestock farmers and promote animal husbandry. This scheme provides financial assistance to farmers for purchasing livestock such as goats, buffaloes, and cows. To qualify, applicants must be permanent residents of Haryana and provide essential documents including an Aadhar Card, mobile number, Voter ID, PAN Card, and a passport-size photograph. The scheme aims to enhance the livelihoods of livestock farmers by offering loans that are specifically tailored to their needs. However, the scheme is currently limited to Haryana. Interested farmers must approach the nearest bank in Haryana, complete the Know Your Customer (KYC) form, and undergo verification to receive the Pashu Credit Card. This initiative is crucial for improving the productivity and economic stability of livestock farmers in the region.</p>
            </div>
            <div className="card"><h3 className="heading">National Agriculture Market (e-NAM)</h3>
                <p className="text">The National Agriculture Market (e-NAM) is a transformative initiative by the Ministry of Agriculture and Farmers' Welfare aimed at modernizing agricultural markets in India. The platform, managed by the Small Farmers Agribusiness Consortium (SFAC), integrates over 200 mandis across the country to facilitate online trading of agricultural produce. e-NAM provides a transparent trading environment by showcasing real-time prices based on supply and demand, thereby ensuring fair price discovery for farmers. It also promotes quality-based auctions and timely payments to reduce transaction costs. Indian farmers can benefit from the platform by registering on the official e-NAM website, providing necessary details, and logging in. Following document submission and approval by Agricultural Produce Market Committees (APMCs), farmers gain full access to the platform. e-NAM represents a significant step towards creating an efficient and transparent agricultural market system.</p>
            </div>
            <div className="card"><h3 className="heading">National Mission for Sustainable Agriculture (NMSA)</h3>
                <p className="text">The National Mission for Sustainable Agriculture (NMSA) is a key component of the National Action Plan on Climate Change (NAPCC) aimed at promoting sustainable agricultural practices in India. The mission focuses on enhancing agricultural productivity through improved water use efficiency, integrated farming systems, resource conservation, and soil health management. It includes several sub-schemes such as Soil Health Management, Rainfed Area Development, and Paramparagat Krishi Vikas Yojana (PKVY). NMSA is designed to address the challenges posed by climate change and ensure sustainable agricultural growth. The mission is targeted at all Indian farmers, although it primarily benefits large-scale farmers due to its extensive focus on technology and infrastructure. To participate, farmers need to register on the official NMSA website, select the relevant sub-scheme, and provide the required details. This initiative plays a crucial role in improving agricultural practices and resource management in the face of climate challenges.</p>
            </div>
            <div className="card"><h3 className="heading">Gramin Bhandaran Yojana</h3>
                <p className="text">The Gramin Bhandaran Yojana is a significant scheme designed to improve rural storage facilities for agricultural produce. By providing financial assistance for the construction and renovation of warehouses, this scheme aims to reduce post-harvest losses and enhance food security. The establishment of these rural warehouses helps farmers store their produce safely, leading to better price realization and reduced wastage. The scheme benefits include improved storage conditions, increased market access, and better management of agricultural produce. Eligible farmers and entities can apply for subsidies under this scheme. To apply, visit the official website, complete the registration process, and submit the necessary details for subsidy approval. This initiative is vital for strengthening rural infrastructure and supporting the agricultural sector.</p>
            </div>
            <div className="card"><h3 className="heading">Modified Interest Subvention Scheme (MISS)</h3>
                <p className="text">The Modified Interest Subvention Scheme (MISS) is a pivotal program aimed at providing concessional short-term loans to farmers involved in crop production and allied activities. Under this scheme, farmers can avail themselves of short-term crop loans up to Rs. 3 lakh at an annual interest rate of 7%. An additional 3% subvention is provided for timely repayment, reducing the effective interest rate to 4% per annum. The scheme also covers post-harvest loans against Negotiable Warehouse Receipts (NWRs) for small and marginal farmers with Kisan Credit Cards (KCCs) during natural calamities. As of January 5, 2024, over 465 lakh new KCC applications have been sanctioned, with a total credit limit of Rs. 5,69,974 crore. This scheme is essential for supporting farmers during challenging times and ensuring their financial stability through affordable credit.</p>
            </div>
            <div className="card"><h3 className="heading">Agriculture Infrastructure Fund (AIF)</h3>
                <p className="text">The Agriculture Infrastructure Fund (AIF) is a significant initiative launched under the Aatmanirbhar Bharat Package to address infrastructure gaps in the agricultural sector. The fund provides medium to long-term debt financing for post-harvest management and community farming projects. With a total allocation of Rs. 1 lakh crore for FY 2020-21 to FY 2025-26 and support until FY 2032-33, the AIF aims to boost investment in agricultural infrastructure. Loans under this fund come with a 3% interest subvention and credit guarantee coverage for amounts up to Rs. 2 crores. Beneficiaries include farmers, agri-entrepreneurs, start-ups, PACS, FPOs, SHGs, and cooperatives. As of December 31, 2023, Rs. 33,209 crores have been sanctioned for 44,912 projects, mobilizing a total investment of Rs. 56,471 crores. This fund is crucial for modernizing agricultural infrastructure and enhancing productivity.</p>
            </div>
            <div className="card"><h3 className="heading">Formation & Promotion of 10,000 FPOs</h3>
                <p className="text">The Central Sector Scheme for the Formation and Promotion of 10,000 Farmer Producer Organizations (FPOs) is an ambitious initiative aimed at empowering farmers through collective action. Launched in 2020 with a total budgetary outlay of Rs. 6865 crores, this scheme focuses on the formation and professional support of FPOs over a five-year period. The scheme is implemented through various agencies that engage Cluster Based Business Organizations (CBBOs) to facilitate the creation and development of FPOs. These organizations help in providing necessary training, support, and resources to the newly formed FPOs. The objective is to enhance farmers' bargaining power, improve access to markets, and ensure better prices for their produce. This initiative is crucial for promoting cooperative farming practices and improving the overall efficiency and profitability of the agricultural sector.</p>
            </div>
            <div className="card"><h3 className="heading">Kisan Credit Card (KCC)</h3>
                <p className="text">The Kisan Credit Card (KCC) scheme is designed to provide timely and adequate credit to farmers for their agricultural needs. It offers a convenient and accessible means for farmers to obtain loans for crop production, post-harvest expenses, and consumption needs. The KCC scheme simplifies the process of obtaining credit by offering loans at concessional interest rates, thereby reducing the financial burden on farmers. To apply for a KCC, farmers need to approach their nearest bank, complete the KCC application form, and provide necessary documents such as identity proof and land records. This scheme plays a vital role in ensuring that farmers have access to the financial resources required for successful agricultural operations and helps in stabilizing their income.</p>
            </div>
            <div className="card"><h3 className="heading">Agricultural Technology Management Agency (ATMA)</h3>
                <p className="text">The Agricultural Technology Management Agency (ATMA) scheme aims to strengthen agricultural extension services by providing comprehensive support to farmers. This includes offering information, training, and resources to help farmers adopt innovative technologies and best practices in agriculture. The ATMA scheme promotes the use of modern agricultural techniques to enhance productivity, income, and overall farm efficiency. Farmers can benefit from various training programs, demonstrations, and field visits organized by ATMA. To participate, farmers need to contact their district ATMA office and register for the desired programs. The scheme plays a crucial role in improving agricultural practices and ensuring that farmers stay updated with the latest developments in the field.</p>
            </div>
            <div className="card"><h3 className="heading">Weather-Based Crop Insurance Scheme (WBCIS)</h3>
                <p className="text">The Weather-Based Crop Insurance Scheme (WBCIS) is designed to provide financial protection to farmers against crop losses caused by adverse weather conditions. The scheme covers losses due to events such as drought, floods, and frost, which can significantly impact crop yield. By compensating for these weather-related risks, WBCIS helps farmers manage the financial impact of unpredictable weather patterns. Farmers can enroll in the scheme through their banks or insurance companies by submitting the required documents and paying the premium based on their crop and location. This insurance scheme is essential for mitigating risks and ensuring that farmers have a safety net during challenging weather conditions.</p>
            </div>
        </div>
    );
}

