const languages = {
    "or": "Oriya / India / 🇮🇳",
    "gu": "Gujarati / India / 🇮🇳",
    "hi": "Hindi / India / 🇮🇳",
    "kn": "Kannada / India / 🇮🇳",
    "ml": "Malayalam / India / 🇮🇳",
    "mr": "Marathi / India / 🇮🇳",
    "pa": "Punjabi / India / 🇮🇳",
    "te": "Telugu / India / 🇮🇳",
    "af": "Afrikaans / South Africa / 🇿🇦",
    "am": "Amharic / Ethiopia / 🇪🇹",
    "ar": "Arabic / Saudi Arabia / 🇸🇦",
    "az": "Azerbaijani / Azerbaijan / 🇦🇿",
    "be": "Belarusian / Belarus / 🇧🇾",
    "bg": "Bulgarian / Bulgaria / 🇧🇬",
    "bn": "Bengali / Bangladesh / 🇧🇩",
    "bs": "Bosnian / Bosnia and Herzegovina / 🇧🇦",
    "ca": "Catalan / Catalonia / 🇦🇩",
    "ceb": "Cebuano / Philippines / 🇵🇭",
    "co": "Corsican / Corsica / 🇨🇷",
    "cs": "Czech / Czech Republic / 🇨🇿",
    "cy": "Welsh / Wales / 🏴",
    "da": "Danish / Denmark / 🇩🇰",
    "de": "German / Germany / 🇩🇪",
    "el": "Greek / Greece / 🇬🇷",
    "en": "English / United Kingdom / 🇬🇧",
    "eo": "Esperanto / Esperanto Community / 🇪🇺",
    "es": "Spanish / Spain / 🇪🇸",
    "et": "Estonian / Estonia / 🇪🇪",
    "eu": "Basque / Basque Country / 🇪🇺",
    "fa": "Persian / Iran / 🇮🇷",
    "fi": "Finnish / Finland / 🇫🇮",
    "fr": "French / France / 🇫🇷",
    "fy": "Frisian / Netherlands / 🇳🇱",
    "ga": "Irish / Ireland / 🇮🇪",
    "gd": "Scots Gaelic / Scotland / 🏴",
    "gl": "Galician / Galicia / 🇪🇸",
    "ha": "Hausa / Nigeria / 🇳🇬",
    "haw": "Hawaiian / United States / 🇺🇸",
    "hmn": "Hmong / China / 🇨🇳",
    "hr": "Croatian / Croatia / 🇭🇷",
    "ht": "Haitian Creole / Haiti / 🇭🇹",
    "hu": "Hungarian / Hungary / 🇭🇺",
    "hy": "Armenian / Armenia / 🇦🇲",
    "id": "Indonesian / Indonesia / 🇮🇩",
    "ig": "Igbo / Nigeria / 🇳🇬",
    "is": "Icelandic / Iceland / 🇮🇸",
    "it": "Italian / Italy / 🇮🇹",
    "iw": "Hebrew / Israel / 🇮🇱",
    "ja": "Japanese / Japan / 🇯🇵",
    "jw": "Javanese / Indonesia / 🇮🇩",
    "ka": "Georgian / Georgia / 🇬🇪",
    "kk": "Kazakh / Kazakhstan / 🇰🇿",
    "km": "Khmer / Cambodia / 🇰🇭",
    "ko": "Korean / South Korea / 🇰🇷",
    "ku": "Kurdish / Iraq / 🇮🇶",
    "ky": "Kyrgyz / Kyrgyzstan / 🇰🇬",
    "la": "Latin / Vatican City / 🇻🇦",
    "lb": "Luxembourgish / Luxembourg / 🇱🇺",
    "lo": "Lao / Laos / 🇱🇦",
    "lt": "Lithuanian / Lithuania / 🇱🇹",
    "lv": "Latvian / Latvia / 🇱🇻",
    "mg": "Malagasy / Madagascar / 🇲🇬",
    "mi": "Maori / New Zealand / 🇳🇿",
    "mk": "Macedonian / North Macedonia / 🇲🇰",
    "mn": "Mongolian / Mongolia / 🇲🇳",
    "ms": "Malay / Malaysia / 🇲🇾",
    "mt": "Maltese / Malta / 🇲🇹",
    "my": "Burmese / Myanmar / 🇲🇲",
    "ne": "Nepali / Nepal / 🇳🇵",
    "nl": "Dutch / Netherlands / 🇳🇱",
    "no": "Norwegian / Norway / 🇳🇴",
    "ny": "Chichewa / Malawi / 🇲🇼",
    "pl": "Polish / Poland / 🇵🇱",
    "ps": "Pashto / Afghanistan / 🇦🇫",
    "pt": "Portuguese / Portugal / 🇵🇹",
    "ro": "Romanian / Romania / 🇷🇴",
    "ru": "Russian / Russia / 🇷🇺",
    "sd": "Sindhi / Pakistan / 🇵🇰",
    "si": "Sinhala / Sri Lanka / 🇱🇰",
    "sk": "Slovak / Slovakia / 🇸🇰",
    "sl": "Slovenian / Slovenia / 🇸🇮",
    "sm": "Samoan / Samoa / 🇼🇸",
    "sn": "Shona / Zimbabwe / 🇿🇼",
    "so": "Somali / Somalia / 🇸🇴",
    "sq": "Albanian / Albania / 🇦🇱",
    "sr": "Serbian / Serbia / 🇷🇸",
    "st": "Sesotho / Lesotho / 🇱🇸",
    "su": "Sundanese / Indonesia / 🇮🇩",
    "sv": "Swedish / Sweden / 🇸🇪",
    "sw": "Swahili / Kenya / 🇰🇪",
    "ta": "Tamil / Sri Lanka / 🇱🇰",
    "tg": "Tajik / Tajikistan / 🇹🇯",
    "th": "Thai / Thailand / 🇹🇭",
    "tl": "Filipino / Philippines / 🇵🇭",
    "tr": "Turkish / Turkey / 🇹🇷",
    "ug": "Uyghur / China / 🇨🇳",
    "uk": "Ukrainian / Ukraine / 🇺🇦",
    "ur": "Urdu / Pakistan / 🇵🇰",
    "uz": "Uzbek / Uzbekistan / 🇺🇿",
    "vi": "Vietnamese / Vietnam / 🇻🇳",
    "xh": "Xhosa / South Africa / 🇿🇦",
    "yi": "Yiddish / Israel / 🇮🇱",
    "yo": "Yoruba / Nigeria / 🇳🇬",
    "zh-cn": "Chinese (Simplified) / China / 🇨🇳",
    "zh-tw": "Chinese (Traditional) / Taiwan / 🇹🇼",
    "zu": "Zulu / South Africa / 🇿🇦"
  }
  
export default languages